### ISSUE TITLE
Is web3's signature the same as the signature here?

### ISSUE THREAD

**Issue by aaronluoq** [ApeWorX/eth-keys#28]
* Version: 0.1.0b3
* Python: 3.4
* OS: osx

### What was wrong?

> In [1]: from eth_keys import keys
> In [2]: pk = keys.PrivateKey(b'\x01' * 32)
> In [3]: signature1 = pk.sign_msg(b'a message')
> In [4]: signature1
> Out[4]: '0xccda990dba7864b79dc49158fea269338a1cf5747bc4c4bf1b96823e31a0997e7d1e65c06c5bf128b7109e1b4b9ba8d1305dc33f32f624695b2fa8e02c12c1e000'

web3.personal.unlockAccount('0x1a642f0e3c3af545e7acbd38b07251b3990914f1','micai123')
Out[26]: True

In [27]: signature2 = web3.eth.sign('0x1a642f0e3c3af545e7acbd38b07251b3990914f1', b'a message')
Out[27]: '0x30629d95501f337e761788734f56b528846db2200e43cb5689d09da97114884b15db98f838f368a9f9d4f1b3e537f2a18ae836bc827419ea03c7126aa7382f661c'

Signature1 and signature2 are different

I would like to know that the package can get the same signature as web3,thx.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by pipermerriam** [comment]
`eth-keys` is a low level tool for doing the ECDSA operations.  it uses canonical `v` values of `0` and `1`, where-as the EVM uses `27` and `28`.

Additionally, I'm not 100% sure that the implementation produces deterministic signatures.

Additionally, `web3.eth.sign` prefixes the message being signed prior to signing it.

So....

1. They aren't expected to be the same due to the differences in `v` values
2. They *may* not be the same even if you make the `v` values the same.
3. They won't be the same due to the appended prefix used in `web3.eth.sign`.
